// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4ZbdsmgdC_g3i1iFHbcDtbZSpgpTdBoI',
    appId: '1:812462846912:web:c00768aecf7e9484000e25',
    messagingSenderId: '812462846912',
    projectId: 'newloginapp-9f026',
    authDomain: 'newloginapp-9f026.firebaseapp.com',
    storageBucket: 'newloginapp-9f026.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA29aFgHeTa0V8f4Erb5iVQuYgfieXV47w',
    appId: '1:812462846912:android:21793b7dba23511a000e25',
    messagingSenderId: '812462846912',
    projectId: 'newloginapp-9f026',
    storageBucket: 'newloginapp-9f026.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI6G73OObv-QC6ExSQcWijx4H8o5ENOLM',
    appId: '1:812462846912:ios:d43472910d141f61000e25',
    messagingSenderId: '812462846912',
    projectId: 'newloginapp-9f026',
    storageBucket: 'newloginapp-9f026.appspot.com',
    iosBundleId: 'com.example.flutterproject',
  );
}
